### ISSUE TITLE
should give 400 status code on invalid query params

### ISSUE THREAD

**Issue by derhuerst** [juliuste/bahn.guru#1]
`bahn.guru` should, if requested with invalid query parameters, return a `400 Bad Request` and maybe redirect to `/`. This let's browsers not cache the URL, the form input. It also tells crawlers & bots that they're requesting an invalid page.

**Comment by juliuste** [comment]
your mudder should give 400 status code on invalid query params

**Comment by derhuerst** [comment]
See my comments.
