### ISSUE TITLE
Departure/Arrival time input fields are too small

### ISSUE THREAD

**Issue by dirkschumacher** [juliuste/bahn.guru#2]
I am using it with Chrome on a Mac and the departure times are barely visible.

<img width="232" alt="" src="https://cloud.githubusercontent.com/assets/1569647/19213595/ec9019d4-8d6f-11e6-84eb-b7ec7c340b6c.png">

**Comment by derhuerst** [comment]
is this still up to date?

**Comment by dirkschumacher** [comment]
Fixed i think

Am 21.12.2016 5:18 nachm. schrieb "Jannis Redmann" <notifications@github.com

**Comment by dirkschumacher** [comment]
Fixed i think
