### ISSUE TITLE
Optionally include SuperSparpreisYoung?

### ISSUE THREAD

**Issue by rugk** [juliuste/bahn.guru#22]
It would be great to include an option to include Super Sparpreis Young tickets for <27 y/o people?
Currently they are excluded, even though they are often a lot cheaper.

See:
https://www.bahn.de/p/view/angebot/aktionsangebote/super-sparpreis-young.shtml

**Comment by krmax44** [comment]
Now permanently available!

**Comment by rugk** [comment]
Yeah, so the checkbox could just be "< passenger under age of 27" or so, even in the default Bahn.de search that can be chosen.

**Comment by juliuste** [comment]
Implemented this (shoutout to @baltpeter), should be deployed in 5min or so. Feel free to validate and re-open this issue if something's not working. Thank you for your patience 😅
