### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by rugk** [juliuste/bahn.guru#29]
https://bahn.guru/ is currently down!

It returns a 404.

**Comment by juliuste** [comment]
Thanks for the hint, as far as I can tell this seems to have been a problem with [Digitalocean's app platform](https://www.digitalocean.com/products/app-platform/), on which this website was deployed, and happened every few days. I moved the website to [our kubernetes cluster](https://github.com/public-transport/infrastructure) now, hope this fixes the issue. Please re-open if the problem resurfaces.
