### ISSUE TITLE
bahn.guru is not responding

### ISSUE THREAD

**Issue by mablae** [juliuste/bahn.guru#6]
Connection timed out...

**Comment by derhuerst** [comment]
@juliuste told me he's having problems with his hosting provider. He's working on it.

**Comment by derhuerst** [comment]
we deployed a temporary version. autocompletion is still broken, but the rest should work, given that the DB API is works.

**Comment by juliuste** [comment]
Fixed it now.

**Comment by mablae** [comment]
^^ DNS resolving issues now (at least for me)

**Comment by derhuerst** [comment]
@mablae cannot confirm this. make sure you use a DNS server that doesn't cache this for too long. those of many routers in Germany do unfortunately.
