### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by juliuste** [juliuste/bahn.guru#7]
The site doesn't really work on mobile devices (or any devices that have a non-standard-pc screen size). Sadly, I don't have the time and - even worse - the skill to craft a responsive layout, so if anyone wants to help: Feel free to PR, I'd really appreciate it!

**Comment by DigitalDesignerOnline** [comment]
hi there I can assist with mobile styling your site. what was the end result you wanted for the look and feel as it truncates in size.
