### ISSUE TITLE
Opengraph integration missing

### ISSUE THREAD

**Issue by k-nut** [juliuste/bahn.guru#8]
I recently shared bahn.guru on Slack and was surprised that it did not show the typical preview image and text. I would therefore propose to add some opengraph tags to let the site gain even more traction on social media and eventually take over the world. 😈 🚌
Would you be happy with that? If so I'd gladly provide a PR.

**Comment by derhuerst** [comment]
a useful overview: https://github.com/joshbuchea/HEAD

**Comment by juliuste** [comment]
👍 Thanks for the PR 😛

**Comment by derhuerst** [comment]
While we're at it: A nice, high-resolution icon might be useful to be able to add it to the home screen, for example.

**Comment by juliuste** [comment]
Could you add the headers to the other routes as well? 🙈

**Comment by k-nut** [comment]
I was hoping that you could merge this as a first step so that we can check if it actually works as expected and we like the looks of it (which unfortunately is only possible one the site is live). If we like the result I'm happy to also adapt the other pages 🙃

**Comment by juliuste** [comment]
> I was hoping that you could merge this as a first step so that we can check if it actually works as expected and we like the looks of it (which unfortunately is only possible one the site is live). If we like the result I'm happy to also adapt the other pages 🙃

Done 🙃
